
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Giriþ_Penceresi extends javax.swing.JFrame {

    /**
     * Creates new form Giriþ_Penceresi
     */
    public Giriþ_Penceresi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jText_KullanýcýAdý = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLbl_KullanýcýAdý = new javax.swing.JLabel();
        jLbl_Þifre = new javax.swing.JLabel();
        jBtn_Giriþ = new javax.swing.JButton();
        jCheckBox_Þifre = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jText_KullanýcýAdý.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jText_KullanýcýAdýActionPerformed(evt);
            }
        });
        getContentPane().add(jText_KullanýcýAdý, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 170, 36));

        jPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 270, 170, 38));

        jLbl_KullanýcýAdý.setBackground(new java.awt.Color(0, 0, 0));
        jLbl_KullanýcýAdý.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLbl_KullanýcýAdý.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_KullanýcýAdý.setText("Kullanýcý Adý: ");
        getContentPane().add(jLbl_KullanýcýAdý, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 150, 36));

        jLbl_Þifre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLbl_Þifre.setForeground(new java.awt.Color(0, 0, 0));
        jLbl_Þifre.setText("ÞÝfre: ");
        getContentPane().add(jLbl_Þifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 114, 36));

        jBtn_Giriþ.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jBtn_Giriþ.setForeground(new java.awt.Color(0, 0, 0));
        jBtn_Giriþ.setText("Giriþ Yap");
        jBtn_Giriþ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_GiriþActionPerformed(evt);
            }
        });
        getContentPane().add(jBtn_Giriþ, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 110, 40));

        jCheckBox_Þifre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jCheckBox_Þifre.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBox_Þifre.setText("Þifreyi Göster");
        jCheckBox_Þifre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ÞifreActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox_Þifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fotoðraflar/Yeni Proje.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ÞifreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ÞifreActionPerformed
        if (jCheckBox_Þifre.isSelected())
        {
            jPassword.setEchoChar('\0'); //null
        }
        else
        {
            jPassword.setEchoChar('*');
        }

    }//GEN-LAST:event_jCheckBox_ÞifreActionPerformed

    private void jPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordActionPerformed

    private void jBtn_GiriþActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_GiriþActionPerformed

        String K_Ad = "Aysu Erdoðan";
        String Sifre = "1234";
        if (jText_KullanýcýAdý.getText().equals(K_Ad) && jPassword.getText().equals(Sifre))

        {
            Ana_Sayfa ana= new Ana_Sayfa();
            // ye.setVisible(true);
            // JOptionPane.showMessageDialog(ye, "Giriþ Baþarýlý");

            int input = JOptionPane.showConfirmDialog(null, "Giriþ Baþarýlý");
            //JOptionPane.showConfirmDialog(ye, "Giriþ Baþarýlý", "Giris", ABORT, HEIGHT)
            // o yes, 1 no, 2 cancel
            if (input==0)
            {
                ana.setVisible(true);
                this.setVisible(false);
            }
            else{}

        }
        else
        {
            JOptionPane.showMessageDialog(null, "Kullanýcý adý veya Þifre yanlýþ");
        }

    }//GEN-LAST:event_jBtn_GiriþActionPerformed

    private void jText_KullanýcýAdýActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jText_KullanýcýAdýActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jText_KullanýcýAdýActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Giriþ_Penceresi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Giriþ_Penceresi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Giriþ_Penceresi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Giriþ_Penceresi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Giriþ_Penceresi().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtn_Giriþ;
    private javax.swing.JCheckBox jCheckBox_Þifre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLbl_KullanýcýAdý;
    private javax.swing.JLabel jLbl_Þifre;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jText_KullanýcýAdý;
    // End of variables declaration//GEN-END:variables
}
