/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Menü_pizza extends javax.swing.JFrame {

    /**
     * Creates new form Menü_pizza
     */
    public Menü_pizza() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadio_kasar2 = new javax.swing.JRadioButton();
        jRadio_kasar1 = new javax.swing.JRadioButton();
        jRadio_kasar3 = new javax.swing.JRadioButton();
        jRadio_sucuk1 = new javax.swing.JRadioButton();
        jRadio_sucuk2 = new javax.swing.JRadioButton();
        jRadio_sucuk3 = new javax.swing.JRadioButton();
        jRadio_kasar4 = new javax.swing.JRadioButton();
        jRadio_salam1 = new javax.swing.JRadioButton();
        jRadio_salam2 = new javax.swing.JRadioButton();
        jRadio_salam3 = new javax.swing.JRadioButton();
        jRadio_sucuk4 = new javax.swing.JRadioButton();
        jRadio_salam4 = new javax.swing.JRadioButton();
        jRadio_mantar1 = new javax.swing.JRadioButton();
        jRadio_mantar2 = new javax.swing.JRadioButton();
        jRadio_mantar3 = new javax.swing.JRadioButton();
        jRadio_mantar4 = new javax.swing.JRadioButton();
        jRadio_zeytin1 = new javax.swing.JRadioButton();
        jRadio_zeytin2 = new javax.swing.JRadioButton();
        jRadio_zeytin3 = new javax.swing.JRadioButton();
        jRadio_zeytin4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jRadio_boyut1 = new javax.swing.JRadioButton();
        jRadio_boyut2 = new javax.swing.JRadioButton();
        jRadio_boyut3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_indirim = new javax.swing.JLabel();
        lbl_hesap = new javax.swing.JLabel();
        btn_siparis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pizzanýzý Nasýl Alýrsýnýz ?");

        buttonGroup2.add(jRadio_kasar2);
        jRadio_kasar2.setText("Orta");

        buttonGroup2.add(jRadio_kasar1);
        jRadio_kasar1.setText("Ekstra");

        buttonGroup2.add(jRadio_kasar3);
        jRadio_kasar3.setText("Az");
        jRadio_kasar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_kasar3ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadio_sucuk1);
        jRadio_sucuk1.setText("Exstra");
        jRadio_sucuk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_sucuk1ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadio_sucuk2);
        jRadio_sucuk2.setText("Orta");
        jRadio_sucuk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_sucuk2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadio_sucuk3);
        jRadio_sucuk3.setText("Az");
        jRadio_sucuk3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_sucuk3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadio_kasar4);
        jRadio_kasar4.setText("Yok");
        jRadio_kasar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_kasar4ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadio_salam1);
        jRadio_salam1.setText("Ekstra");
        jRadio_salam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_salam1ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadio_salam2);
        jRadio_salam2.setText("Orta");

        buttonGroup4.add(jRadio_salam3);
        jRadio_salam3.setText("Az");

        buttonGroup3.add(jRadio_sucuk4);
        jRadio_sucuk4.setText("Yok");

        buttonGroup4.add(jRadio_salam4);
        jRadio_salam4.setText("Yok");
        jRadio_salam4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_salam4ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadio_mantar1);
        jRadio_mantar1.setText("Ekstra");

        buttonGroup5.add(jRadio_mantar2);
        jRadio_mantar2.setText("Orta");

        buttonGroup5.add(jRadio_mantar3);
        jRadio_mantar3.setText("Az");
        jRadio_mantar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_mantar3ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadio_mantar4);
        jRadio_mantar4.setText("Yok");

        buttonGroup6.add(jRadio_zeytin1);
        jRadio_zeytin1.setText("Ekstra");
        jRadio_zeytin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_zeytin1ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadio_zeytin2);
        jRadio_zeytin2.setText("Orta");

        buttonGroup6.add(jRadio_zeytin3);
        jRadio_zeytin3.setText("Az");

        buttonGroup6.add(jRadio_zeytin4);
        jRadio_zeytin4.setText("Yok");

        jLabel2.setText("Salam");

        buttonGroup1.add(jRadio_boyut1);
        jRadio_boyut1.setText("Büyük");

        buttonGroup1.add(jRadio_boyut2);
        jRadio_boyut2.setText("Orta");
        jRadio_boyut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_boyut2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_boyut3);
        jRadio_boyut3.setText("Küçük");
        jRadio_boyut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_boyut3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Boyut");

        jLabel4.setText("Kaþar");

        jLabel5.setText("Sucuk");

        jLabel6.setText("Mantar");

        jLabel7.setText("Zeytin");

        lbl_indirim.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lbl_indirim.setForeground(new java.awt.Color(153, 0, 51));
        lbl_indirim.setText("INDIRIM: 0TL");

        lbl_hesap.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lbl_hesap.setForeground(new java.awt.Color(0, 153, 0));
        lbl_hesap.setText("Hesap: 0TL");

        btn_siparis.setText("Sipariþ ver");
        btn_siparis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_siparisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(342, 342, 342)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_indirim, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadio_boyut1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadio_kasar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadio_sucuk1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadio_salam1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadio_mantar1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadio_zeytin1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_kasar2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_kasar3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_kasar4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_boyut2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadio_boyut3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_sucuk2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_sucuk3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_sucuk4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_salam2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_salam3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_salam4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_mantar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_mantar3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_mantar4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadio_zeytin2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_zeytin3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadio_zeytin4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14)
                        .addComponent(btn_siparis, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(190, 190, 190))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_boyut1)
                    .addComponent(jRadio_boyut2)
                    .addComponent(jRadio_boyut3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_kasar1)
                    .addComponent(jRadio_kasar2)
                    .addComponent(jRadio_kasar3)
                    .addComponent(jRadio_kasar4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_indirim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadio_sucuk1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadio_sucuk2)
                        .addComponent(jRadio_sucuk3)
                        .addComponent(jRadio_sucuk4)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lbl_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_salam1)
                            .addComponent(jRadio_salam2)
                            .addComponent(jRadio_salam3)
                            .addComponent(jRadio_salam4))))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_mantar1)
                            .addComponent(jRadio_mantar2)
                            .addComponent(jRadio_mantar3)
                            .addComponent(jRadio_mantar4))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_siparis, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_zeytin1)
                    .addComponent(jRadio_zeytin2)
                    .addComponent(jRadio_zeytin3)
                    .addComponent(jRadio_zeytin4))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio_sucuk3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_sucuk3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_sucuk3ActionPerformed

    private void jRadio_sucuk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_sucuk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_sucuk2ActionPerformed

    private void jRadio_sucuk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_sucuk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_sucuk1ActionPerformed

    private void jRadio_salam4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_salam4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_salam4ActionPerformed

    private void jRadio_zeytin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_zeytin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_zeytin1ActionPerformed

    private void jRadio_mantar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_mantar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_mantar3ActionPerformed

    private void jRadio_kasar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_kasar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_kasar4ActionPerformed

    private void jRadio_kasar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_kasar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_kasar3ActionPerformed

    private void jRadio_salam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_salam1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_salam1ActionPerformed

    private void jRadio_boyut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_boyut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_boyut2ActionPerformed

    private void jRadio_boyut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_boyut3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_boyut3ActionPerformed

    private void btn_siparisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_siparisActionPerformed
        int hesap = 0;
        if (jRadio_boyut1.isSelected())
        {
            hesap = hesap+20;
        }
        if (jRadio_boyut2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_boyut3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_kasar1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_kasar2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_kasar3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_mantar1.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_mantar2.isSelected())
        {
            hesap = hesap+8;
        }
        if (jRadio_mantar3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_salam1.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_salam2.isSelected())
        {
            hesap = hesap+7;
        }
        if (jRadio_salam3.isSelected())
        {
            hesap = hesap+3;
        }
        if (jRadio_sucuk1.isSelected())
        {
            hesap = hesap+12;
        }
        if (jRadio_sucuk2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_sucuk3.isSelected())
        {
            hesap = hesap+7;
        }
        if (jRadio_zeytin1.isSelected())
        {
            hesap = hesap+8;
        }
        if (jRadio_zeytin2.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_zeytin3.isSelected())
        {
            hesap = hesap+3;
        }
        
        lbl_hesap.setText("HESAP: " + hesap + "TL");
    }//GEN-LAST:event_btn_siparisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menü_pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menü_pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menü_pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menü_pizza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menü_pizza().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_siparis;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio_boyut1;
    private javax.swing.JRadioButton jRadio_boyut2;
    private javax.swing.JRadioButton jRadio_boyut3;
    private javax.swing.JRadioButton jRadio_kasar1;
    private javax.swing.JRadioButton jRadio_kasar2;
    private javax.swing.JRadioButton jRadio_kasar3;
    private javax.swing.JRadioButton jRadio_kasar4;
    private javax.swing.JRadioButton jRadio_mantar1;
    private javax.swing.JRadioButton jRadio_mantar2;
    private javax.swing.JRadioButton jRadio_mantar3;
    private javax.swing.JRadioButton jRadio_mantar4;
    private javax.swing.JRadioButton jRadio_salam1;
    private javax.swing.JRadioButton jRadio_salam2;
    private javax.swing.JRadioButton jRadio_salam3;
    private javax.swing.JRadioButton jRadio_salam4;
    private javax.swing.JRadioButton jRadio_sucuk1;
    private javax.swing.JRadioButton jRadio_sucuk2;
    private javax.swing.JRadioButton jRadio_sucuk3;
    private javax.swing.JRadioButton jRadio_sucuk4;
    private javax.swing.JRadioButton jRadio_zeytin1;
    private javax.swing.JRadioButton jRadio_zeytin2;
    private javax.swing.JRadioButton jRadio_zeytin3;
    private javax.swing.JRadioButton jRadio_zeytin4;
    private javax.swing.JLabel lbl_hesap;
    private javax.swing.JLabel lbl_indirim;
    // End of variables declaration//GEN-END:variables
}
