/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Menü_dürüm extends javax.swing.JFrame {

    /**
     * Creates new form Menü_dürüm
     */
    public Menü_dürüm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadio_boyut1 = new javax.swing.JRadioButton();
        jRadio_boyut2 = new javax.swing.JRadioButton();
        jRadio_boyut3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadio_cesit1 = new javax.swing.JRadioButton();
        jRadio_cesit2 = new javax.swing.JRadioButton();
        jRadio_cesit3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadio_yanurun1 = new javax.swing.JRadioButton();
        jRadio_yanurun2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadio_yanboy1 = new javax.swing.JRadioButton();
        jRadio_yanboy2 = new javax.swing.JRadioButton();
        jRadio_yanboy3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadio_ýcecek1 = new javax.swing.JRadioButton();
        jRadio_ýcecek2 = new javax.swing.JRadioButton();
        jRadio_ýcecek3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadio_ýcecekboy1 = new javax.swing.JRadioButton();
        jRadio_ýcecekboy2 = new javax.swing.JRadioButton();
        jRadio_ýcecekboy3 = new javax.swing.JRadioButton();
        jLbl_hesap = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dürümünüzü nasýl alýrdýnýz?");

        jLabel2.setText("Boyut");

        buttonGroup1.add(jRadio_boyut1);
        jRadio_boyut1.setText("Büyük");

        buttonGroup1.add(jRadio_boyut2);
        jRadio_boyut2.setText("Orta");
        jRadio_boyut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_boyut2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadio_boyut3);
        jRadio_boyut3.setText("Küçük");

        jLabel3.setText("Et Türü");

        buttonGroup2.add(jRadio_cesit1);
        jRadio_cesit1.setText("Kýrmýzý Et");

        buttonGroup2.add(jRadio_cesit2);
        jRadio_cesit2.setText("Tavuk Eti");

        buttonGroup2.add(jRadio_cesit3);
        jRadio_cesit3.setText("Balýk Eti");
        jRadio_cesit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_cesit3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Yan Ürün");

        buttonGroup3.add(jRadio_yanurun1);
        jRadio_yanurun1.setText("Patates Kýzartmasý");

        buttonGroup3.add(jRadio_yanurun2);
        jRadio_yanurun2.setText("Salata");
        jRadio_yanurun2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_yanurun2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Yan Ürün Boyutu");

        buttonGroup4.add(jRadio_yanboy1);
        jRadio_yanboy1.setText("Büyük");

        buttonGroup4.add(jRadio_yanboy2);
        jRadio_yanboy2.setText("Orta");

        buttonGroup4.add(jRadio_yanboy3);
        jRadio_yanboy3.setText("Küçük");

        jLabel6.setText("Ýçecek");

        buttonGroup5.add(jRadio_ýcecek1);
        jRadio_ýcecek1.setText("Kola");

        buttonGroup5.add(jRadio_ýcecek2);
        jRadio_ýcecek2.setText("Soda");

        buttonGroup5.add(jRadio_ýcecek3);
        jRadio_ýcecek3.setText("Ayran");

        jLabel7.setText("Ýçecek Boyutu");

        buttonGroup6.add(jRadio_ýcecekboy1);
        jRadio_ýcecekboy1.setText("Büyük");

        buttonGroup6.add(jRadio_ýcecekboy2);
        jRadio_ýcecekboy2.setText("Orta");

        buttonGroup6.add(jRadio_ýcecekboy3);
        jRadio_ýcecekboy3.setText("Küçük");

        jLbl_hesap.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLbl_hesap.setForeground(new java.awt.Color(0, 153, 0));
        jLbl_hesap.setText("HESAP : 0TL");

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadio_cesit1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_cesit2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadio_cesit3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(jLbl_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadio_boyut1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadio_boyut2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_boyut3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadio_yanurun1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_yanurun2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(208, 208, 208)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadio_yanboy1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_yanboy2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_yanboy3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadio_ýcecek1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadio_ýcecek2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_ýcecek3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadio_ýcecekboy1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_ýcecekboy2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadio_ýcecekboy3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_boyut1)
                            .addComponent(jRadio_boyut2)
                            .addComponent(jRadio_boyut3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_cesit1)
                            .addComponent(jRadio_cesit2)
                            .addComponent(jRadio_cesit3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_yanurun1)
                            .addComponent(jRadio_yanurun2)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLbl_hesap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_yanboy1)
                    .addComponent(jRadio_yanboy2)
                    .addComponent(jRadio_yanboy3))
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_ýcecek1)
                    .addComponent(jRadio_ýcecek2)
                    .addComponent(jRadio_ýcecek3))
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_ýcecekboy1)
                    .addComponent(jRadio_ýcecekboy2)
                    .addComponent(jRadio_ýcecekboy3))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadio_cesit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_cesit3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_cesit3ActionPerformed

    private void jRadio_boyut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_boyut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_boyut2ActionPerformed

    private void jRadio_yanurun2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_yanurun2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_yanurun2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int hesap = 0;
        if (jRadio_boyut1.isSelected())
        {
            hesap = hesap+20;
        }
        if (jRadio_boyut2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_boyut3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_cesit1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_cesit2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_cesit3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_yanboy1.isSelected())
        {
            hesap = hesap+20;
        }
        if (jRadio_yanboy2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_yanboy3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_yanurun1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_yanurun2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_ýcecek1.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_ýcecek2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_ýcecek3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_ýcecekboy1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_ýcecekboy2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_ýcecekboy3.isSelected())
        {
            hesap = hesap+5;
        }
        
        jLbl_hesap.setText("HESAP: " + hesap + "TL");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menü_dürüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menü_dürüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menü_dürüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menü_dürüm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menü_dürüm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLbl_hesap;
    private javax.swing.JRadioButton jRadio_boyut1;
    private javax.swing.JRadioButton jRadio_boyut2;
    private javax.swing.JRadioButton jRadio_boyut3;
    private javax.swing.JRadioButton jRadio_cesit1;
    private javax.swing.JRadioButton jRadio_cesit2;
    private javax.swing.JRadioButton jRadio_cesit3;
    private javax.swing.JRadioButton jRadio_yanboy1;
    private javax.swing.JRadioButton jRadio_yanboy2;
    private javax.swing.JRadioButton jRadio_yanboy3;
    private javax.swing.JRadioButton jRadio_yanurun1;
    private javax.swing.JRadioButton jRadio_yanurun2;
    private javax.swing.JRadioButton jRadio_ýcecek1;
    private javax.swing.JRadioButton jRadio_ýcecek2;
    private javax.swing.JRadioButton jRadio_ýcecek3;
    private javax.swing.JRadioButton jRadio_ýcecekboy1;
    private javax.swing.JRadioButton jRadio_ýcecekboy2;
    private javax.swing.JRadioButton jRadio_ýcecekboy3;
    // End of variables declaration//GEN-END:variables
}
