/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Menü_hamburger extends javax.swing.JFrame {

    /**
     * Creates new form Menü_hamburger
     */
    public Menü_hamburger() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioboyut1 = new javax.swing.JRadioButton();
        jRadioboyut2 = new javax.swing.JRadioButton();
        jRadioboyut3 = new javax.swing.JRadioButton();
        jRadio_yan1 = new javax.swing.JRadioButton();
        jRadio_yan2 = new javax.swing.JRadioButton();
        jRadio_yan3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jRadio_yanboy1 = new javax.swing.JRadioButton();
        jRadio_yanboy2 = new javax.swing.JRadioButton();
        jRadio_yanboy3 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadio_icecek1 = new javax.swing.JRadioButton();
        jRadio_icecek2 = new javax.swing.JRadioButton();
        jRadio_icecek3 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadio_icecekboy1 = new javax.swing.JRadioButton();
        jRadio_icecekboy2 = new javax.swing.JRadioButton();
        jRadio_icecekboy3 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        lbl_hesap = new javax.swing.JLabel();
        btn_hesapla = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Hamburgerinizi Nasýl Alýrsýnýz?");

        jLabel2.setText("Boyut");

        jLabel3.setText("Yan ürünler");

        buttonGroup1.add(jRadioboyut1);
        jRadioboyut1.setText("Büyük");
        jRadioboyut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioboyut1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioboyut2);
        jRadioboyut2.setText("Orta");
        jRadioboyut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioboyut2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioboyut3);
        jRadioboyut3.setText("Küçük");

        buttonGroup2.add(jRadio_yan1);
        jRadio_yan1.setText("Patates Kýzartmasý");

        buttonGroup2.add(jRadio_yan2);
        jRadio_yan2.setText("Soðan Halkasý");

        buttonGroup2.add(jRadio_yan3);
        jRadio_yan3.setText("Tavuk Kanadý");

        jLabel4.setText("Yan ürün boyutu");

        buttonGroup3.add(jRadio_yanboy1);
        jRadio_yanboy1.setText("Büyük");

        buttonGroup3.add(jRadio_yanboy2);
        jRadio_yanboy2.setText("Orta");
        jRadio_yanboy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadio_yanboy2ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadio_yanboy3);
        jRadio_yanboy3.setText("Küçük");

        jLabel5.setText("Ýçecek");

        buttonGroup4.add(jRadio_icecek1);
        jRadio_icecek1.setText("Kola");

        buttonGroup4.add(jRadio_icecek2);
        jRadio_icecek2.setText("Soda");

        buttonGroup4.add(jRadio_icecek3);
        jRadio_icecek3.setText("Fanta");

        jLabel6.setText("Ýçecek Boyutu");

        buttonGroup5.add(jRadio_icecekboy1);
        jRadio_icecekboy1.setText("Büyük");

        buttonGroup5.add(jRadio_icecekboy2);
        jRadio_icecekboy2.setText("Orta");

        buttonGroup5.add(jRadio_icecekboy3);
        jRadio_icecekboy3.setText("Küçük");

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("INDIRIM: 0TL");

        lbl_hesap.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        lbl_hesap.setForeground(new java.awt.Color(0, 153, 0));
        lbl_hesap.setText("HESAP: 0TL");

        btn_hesapla.setText("Hesapla");
        btn_hesapla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hesaplaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_yan1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadio_yan2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio_yan3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioboyut1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioboyut2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioboyut3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_yanboy1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio_yanboy2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadio_yanboy3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(lbl_hesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btn_hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_icecek1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadio_icecek2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio_icecek3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_icecekboy1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadio_icecekboy2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadio_icecekboy3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioboyut1)
                    .addComponent(jRadioboyut2)
                    .addComponent(jRadioboyut3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_yan1)
                            .addComponent(jRadio_yan2)
                            .addComponent(jRadio_yan3)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_yanboy1)
                            .addComponent(jRadio_yanboy2)
                            .addComponent(jRadio_yanboy3))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_hesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(10, 10, 10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_icecek1)
                    .addComponent(jRadio_icecek2)
                    .addComponent(jRadio_icecek3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_hesapla, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_icecekboy1)
                            .addComponent(jRadio_icecekboy2)
                            .addComponent(jRadio_icecekboy3))
                        .addGap(85, 85, 85))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioboyut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioboyut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioboyut2ActionPerformed

    private void jRadio_yanboy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadio_yanboy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadio_yanboy2ActionPerformed

    private void jRadioboyut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioboyut1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioboyut1ActionPerformed

    private void btn_hesaplaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hesaplaActionPerformed
       int hesap = 0;
        if (jRadio_icecek1.isSelected())
        {
            hesap = hesap+20;
        }
        if (jRadio_icecek2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_icecek3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_icecekboy1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_icecekboy2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_icecekboy3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_yan1.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_yan2.isSelected())
        {
            hesap = hesap+8;
        }
        if (jRadio_yan3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_yanboy1.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_yanboy2.isSelected())
        {
            hesap = hesap+7;
        }
        if (jRadio_yanboy3.isSelected())
        {
            hesap = hesap+3;
        }
        if (jRadioboyut1.isSelected())
        {
            hesap = hesap+12;
        }
        if (jRadioboyut2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadioboyut3.isSelected())
        {
            hesap = hesap+7;
        }
        
        
        lbl_hesap.setText("HESAP: " + hesap + "TL");
    }//GEN-LAST:event_btn_hesaplaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menü_hamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menü_hamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menü_hamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menü_hamburger.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menü_hamburger().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hesapla;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton jRadio_icecek1;
    private javax.swing.JRadioButton jRadio_icecek2;
    private javax.swing.JRadioButton jRadio_icecek3;
    private javax.swing.JRadioButton jRadio_icecekboy1;
    private javax.swing.JRadioButton jRadio_icecekboy2;
    private javax.swing.JRadioButton jRadio_icecekboy3;
    private javax.swing.JRadioButton jRadio_yan1;
    private javax.swing.JRadioButton jRadio_yan2;
    private javax.swing.JRadioButton jRadio_yan3;
    private javax.swing.JRadioButton jRadio_yanboy1;
    private javax.swing.JRadioButton jRadio_yanboy2;
    private javax.swing.JRadioButton jRadio_yanboy3;
    private javax.swing.JRadioButton jRadioboyut1;
    private javax.swing.JRadioButton jRadioboyut2;
    private javax.swing.JRadioButton jRadioboyut3;
    private javax.swing.JLabel lbl_hesap;
    // End of variables declaration//GEN-END:variables
}
