/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author DELL
 */
public class Menü_tatlý extends javax.swing.JFrame {

    /**
     * Creates new form Menü_tatlý
     */
    public Menü_tatlý() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadio_boyut1 = new javax.swing.JRadioButton();
        jRadio_boyut2 = new javax.swing.JRadioButton();
        jRadio_boyut3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jRadio_cesit1 = new javax.swing.JRadioButton();
        jRadio_cesit2 = new javax.swing.JRadioButton();
        jRadio_cesit3 = new javax.swing.JRadioButton();
        jRadio_cesit4 = new javax.swing.JRadioButton();
        jRadio_cesit5 = new javax.swing.JRadioButton();
        jRadio_cesit6 = new javax.swing.JRadioButton();
        jRadio_cesit7 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLbl_hesap = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Tatlýnýzý Nasýl Alýrdýnýz?");

        jLabel2.setText("Boyut");

        buttonGroup1.add(jRadio_boyut1);
        jRadio_boyut1.setText("Büyük");

        buttonGroup1.add(jRadio_boyut2);
        jRadio_boyut2.setText("Orta");

        buttonGroup1.add(jRadio_boyut3);
        jRadio_boyut3.setText("Küçük");

        jLabel3.setText("Tatlý Çeþitleri");

        buttonGroup2.add(jRadio_cesit1);
        jRadio_cesit1.setText("Magnolya");

        buttonGroup2.add(jRadio_cesit2);
        jRadio_cesit2.setText("Mozaik pasta");

        buttonGroup2.add(jRadio_cesit3);
        jRadio_cesit3.setText("Kadayýf");

        buttonGroup2.add(jRadio_cesit4);
        jRadio_cesit4.setText("Meyveli Pasta");

        buttonGroup2.add(jRadio_cesit5);
        jRadio_cesit5.setText("Çikolatalý Pasta");

        buttonGroup2.add(jRadio_cesit6);
        jRadio_cesit6.setText("Künefe");

        buttonGroup2.add(jRadio_cesit7);
        jRadio_cesit7.setText("Sütlaç");

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLbl_hesap.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLbl_hesap.setForeground(new java.awt.Color(0, 153, 0));
        jLbl_hesap.setText("HESAP: 0TL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jRadio_cesit6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jRadio_cesit7, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_boyut1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadio_boyut2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadio_boyut3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadio_cesit1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadio_cesit2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jRadio_cesit3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(179, 179, 179)
                        .addComponent(jLbl_hesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(125, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadio_cesit4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRadio_cesit5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(169, 169, 169))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_boyut1)
                            .addComponent(jRadio_boyut2)
                            .addComponent(jRadio_boyut3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadio_cesit1)
                            .addComponent(jRadio_cesit2)
                            .addComponent(jRadio_cesit3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLbl_hesap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadio_cesit4)
                    .addComponent(jRadio_cesit5)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio_cesit6)
                    .addComponent(jRadio_cesit7))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int hesap = 0;
        if (jRadio_boyut1.isSelected())
        {
            hesap = hesap+20;
        }
        if (jRadio_boyut2.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_boyut3.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_cesit1.isSelected())
        {
            hesap = hesap+15;
        }
        if (jRadio_cesit2.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_cesit3.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_cesit4.isSelected())
        {
            hesap = hesap+10;
        }
        if (jRadio_cesit5.isSelected())
        {
            hesap = hesap+8;
        }
        if (jRadio_cesit6.isSelected())
        {
            hesap = hesap+5;
        }
        if (jRadio_cesit7.isSelected())
        {
            hesap = hesap+5;
        }
        jLbl_hesap.setText("HESAP: " + hesap + "TL");
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menü_tatlý.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menü_tatlý.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menü_tatlý.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menü_tatlý.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menü_tatlý().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLbl_hesap;
    private javax.swing.JRadioButton jRadio_boyut1;
    private javax.swing.JRadioButton jRadio_boyut2;
    private javax.swing.JRadioButton jRadio_boyut3;
    private javax.swing.JRadioButton jRadio_cesit1;
    private javax.swing.JRadioButton jRadio_cesit2;
    private javax.swing.JRadioButton jRadio_cesit3;
    private javax.swing.JRadioButton jRadio_cesit4;
    private javax.swing.JRadioButton jRadio_cesit5;
    private javax.swing.JRadioButton jRadio_cesit6;
    private javax.swing.JRadioButton jRadio_cesit7;
    // End of variables declaration//GEN-END:variables
}
